In [109]:
#importing required libraries
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')

In [110]:
#loadind dataset
test= pd.read_csv('/content/drive/MyDrive/Predictive_Data/test_file.csv')
train= pd.read_csv('/content/drive/MyDrive/Predictive_Data/train_file.csv')

In [111]:
train

ID UsageClass  ... PublicationYear  MaterialType
0          1   Physical  ...             NaN          BOOK
1          2   Physical  ...           1998.          BOOK
2          3   Physical  ...          c2002.          BOOK
3          4   Physical  ...             NaN          BOOK
4          5   Physical  ...             NaN          BOOK
...      ...        ...  ...             ...           ...
31648  31649   Physical  ...             NaN          BOOK
31649  31650   Physical  ...             NaN     VIDEOCASS
31650  31651   Physical  ...             NaN     VIDEODISC
31651  31652   Physical  ...          c2004.          BOOK
31652  31653   Physical  ...             NaN         MIXED

[31653 rows x 12 columns]

In [112]:
train.dtypes

ID                  int64
UsageClass         object
CheckoutType       object
CheckoutYear        int64
CheckoutMonth       int64
Checkouts           int64
Title              object
Creator            object
Subjects           object
Publisher          object
PublicationYear    object
MaterialType       object
dtype: object

In [113]:
train.nunique()

ID                 31653
UsageClass             1
CheckoutType           1
CheckoutYear           1
CheckoutMonth          1
Checkouts             50
Title              31653
Creator             6731
Subjects           24755
Publisher           3519
PublicationYear      840
MaterialType           8
dtype: int64

In [114]:
train.drop(['UsageClass',	'CheckoutType', 'CheckoutYear',	'CheckoutMonth', 'Title',	'Creator',	'Subjects',	'Publisher',	'PublicationYear'], 
           axis=1, inplace = True)
train

ID  Checkouts MaterialType
0          1          1         BOOK
1          2          1         BOOK
2          3          3         BOOK
3          4          1         BOOK
4          5          1         BOOK
...      ...        ...          ...
31648  31649          2         BOOK
31649  31650          5    VIDEOCASS
31650  31651         12    VIDEODISC
31651  31652          4         BOOK
31652  31653          2        MIXED

[31653 rows x 3 columns]

In [115]:
pd.unique(train['MaterialType'])

array(['BOOK', 'SOUNDDISC', 'VIDEOCASS', 'VIDEODISC', 'SOUNDCASS',
       'MUSIC', 'MIXED', 'CR'], dtype=object)

In [116]:
train['MaterialType'].replace({'BOOK':0, 'SOUNDDISC':1, 'VIDEOCASS':2, 'VIDEODISC':3, 'SOUNDCASS':4,
       'MUSIC':5, 'MIXED':6, 'CR':7}, inplace=True)
train

ID  Checkouts  MaterialType
0          1          1             0
1          2          1             0
2          3          3             0
3          4          1             0
4          5          1             0
...      ...        ...           ...
31648  31649          2             0
31649  31650          5             2
31650  31651         12             3
31651  31652          4             0
31652  31653          2             6

[31653 rows x 3 columns]

In [117]:
x= train.drop(columns=['MaterialType'])
y= train['MaterialType']
print(x)
print(y)

          ID  Checkouts
0          1          1
1          2          1
2          3          3
3          4          1
4          5          1
...      ...        ...
31648  31649          2
31649  31650          5
31650  31651         12
31651  31652          4
31652  31653          2

[31653 rows x 2 columns]
0        0
1        0
2        0
3        0
4        0
        ..
31648    0
31649    2
31650    3
31651    0
31652    6
Name: MaterialType, Length: 31653, dtype: int64


In [118]:
x.replace([np.inf, -np.inf], np.nan, inplace=True)
y.replace([np.inf, -np.inf], np.nan, inplace=True)
x.fillna(0)
y.fillna(0)

0        0
1        0
2        0
3        0
4        0
        ..
31648    0
31649    2
31650    3
31651    0
31652    6
Name: MaterialType, Length: 31653, dtype: int64

In [119]:
print(x)
print(y)

          ID  Checkouts
0          1          1
1          2          1
2          3          3
3          4          1
4          5          1
...      ...        ...
31648  31649          2
31649  31650          5
31650  31651         12
31651  31652          4
31652  31653          2

[31653 rows x 2 columns]
0        0
1        0
2        0
3        0
4        0
        ..
31648    0
31649    2
31650    3
31651    0
31652    6
Name: MaterialType, Length: 31653, dtype: int64


In [120]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0,test_size=0.2)

In [121]:
print(len(x_test))
print(len(x_train))
print(len(y_test))
print(len(y_train))

6331
25322
6331
25322


In [122]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=7)
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=7)

In [123]:
y_pred=knn.predict(x_test)
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
print("Classification Report is:\n",classification_report(y_test,y_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("Training Score:\n",knn.score(x_train,y_train)*100)

Classification Report is:
               precision    recall  f1-score   support

           0       0.69      0.98      0.81      4376
           1       0.10      0.01      0.02       791
           2       0.07      0.00      0.01       530
           3       0.00      0.00      0.00       303
           4       0.00      0.00      0.00       194
           5       0.00      0.00      0.00        41
           6       0.00      0.00      0.00        76
           7       0.00      0.00      0.00        20

    accuracy                           0.68      6331
   macro avg       0.11      0.12      0.11      6331
weighted avg       0.50      0.68      0.56      6331

Confusion Matrix:
 [[4277   73   21    5    0    0    0    0]
 [ 775   11    3    2    0    0    0    0]
 [ 520    8    2    0    0    0    0    0]
 [ 291   12    0    0    0    0    0    0]
 [ 191    2    1    0    0    0    0    0]
 [  39    2    0    0    0    0    0    0]
 [  73    3    0    0    0    0    0    0]
 [

In [124]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train,y_train)

GaussianNB()

In [125]:
y_pred=gnb.predict(x_test)
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
print("Classification Report is:\n",classification_report(y_test,y_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("Training Score:\n",gnb.score(x_train,y_train)*100)
print(accuracy_score(y_test,y_pred)*100)

Classification Report is:
               precision    recall  f1-score   support

           0       0.70      0.98      0.81      4376
           1       0.00      0.00      0.00       791
           2       0.00      0.00      0.00       530
           3       0.31      0.21      0.25       303
           4       0.00      0.00      0.00       194
           5       0.00      0.00      0.00        41
           6       0.00      0.00      0.00        76
           7       0.00      0.00      0.00        20

    accuracy                           0.68      6331
   macro avg       0.13      0.15      0.13      6331
weighted avg       0.50      0.68      0.57      6331

Confusion Matrix:
 [[4272    0    0  104    0    0    0    0]
 [ 777    0    0   14    0    0    0    0]
 [ 507    0    0   23    0    0    0    0]
 [ 240    0    0   63    0    0    0    0]
 [ 193    0    0    1    0    0    0    0]
 [  41    0    0    0    0    0    0    0]
 [  76    0    0    0    0    0    0    0]
 [

In [126]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier(max_depth=6, random_state=123,criterion='entropy')
dtree.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=6, random_state=123)

In [127]:
from sklearn.metrics import classification_report,mean_squared_error
y_pred=dtree.predict(x_test)
conf =print(confusion_matrix(y_test, y_pred))
clf =print(classification_report(y_test, y_pred))
print("Training Score:\n",dtree.score(x_train,y_train)*100)

[[4339   11    1   24    1    0    0    0]
 [ 787    2    0    2    0    0    0    0]
 [ 520    6    1    3    0    0    0    0]
 [ 284    1    2   16    0    0    0    0]
 [ 194    0    0    0    0    0    0    0]
 [  41    0    0    0    0    0    0    0]
 [  76    0    0    0    0    0    0    0]
 [  20    0    0    0    0    0    0    0]]
              precision    recall  f1-score   support

           0       0.69      0.99      0.82      4376
           1       0.10      0.00      0.00       791
           2       0.25      0.00      0.00       530
           3       0.36      0.05      0.09       303
           4       0.00      0.00      0.00       194
           5       0.00      0.00      0.00        41
           6       0.00      0.00      0.00        76
           7       0.00      0.00      0.00        20

    accuracy                           0.69      6331
   macro avg       0.17      0.13      0.11      6331
weighted avg       0.53      0.69      0.57      6331

Trai

In [128]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
rfc=RandomForestClassifier()
rfc.fit(x_train,y_train)

RandomForestClassifier()

In [129]:
y_pred=rfc.predict(x_test)
conf =print(confusion_matrix(y_test, y_pred))
clf =print(classification_report(y_test, y_pred))
score=accuracy_score(y_test,y_pred)
score
print("Training Score:\n",rfc.score(x_train,y_train)*100)

[[3059  546  383  160  152   23   46    7]
 [ 482  143   83   42   25    6    7    3]
 [ 342   72   51   46   12    1    4    2]
 [ 158   50   33   55    4    1    2    0]
 [ 131   33   19    5    5    1    0    0]
 [  30    5    4    1    0    1    0    0]
 [  54   13    5    1    3    0    0    0]
 [  14    3    1    2    0    0    0    0]]
              precision    recall  f1-score   support

           0       0.72      0.70      0.71      4376
           1       0.17      0.18      0.17       791
           2       0.09      0.10      0.09       530
           3       0.18      0.18      0.18       303
           4       0.02      0.03      0.03       194
           5       0.03      0.02      0.03        41
           6       0.00      0.00      0.00        76
           7       0.00      0.00      0.00        20

    accuracy                           0.52      6331
   macro avg       0.15      0.15      0.15      6331
weighted avg       0.53      0.52      0.53      6331

Trai

In [130]:
test

ID UsageClass  ...                 Publisher  PublicationYear
0      31654   Physical  ...                       NaN              NaN
1      31655   Physical  ...                       NaN              NaN
2      31656   Physical  ...                 Charisma,           p1992.
3      31657   Physical  ...                       NaN              NaN
4      31658   Physical  ...                       NaN              NaN
...      ...        ...  ...                       ...              ...
21097  52751   Physical  ...                       NaN              NaN
21098  52752   Physical  ...  Dutton Children's Books,            2003.
21099  52753   Physical  ...       St. Martin's Press,            1993.
21100  52754   Physical  ...                       NaN              NaN
21101  52755   Physical  ...                Hollywood,           p1989.

[21102 rows x 11 columns]

In [131]:
xtest= test.drop(columns=['UsageClass',	'CheckoutType', 'CheckoutYear',	'CheckoutMonth', 'Title',	'Creator',	'Subjects',	'Publisher',	'PublicationYear'])
xtest
xpred= rfc.predict(xtest)
output= pd.DataFrame({'ID': test.ID, 'MaterialType': xpred})
output

ID  MaterialType
0      31654             0
1      31655             0
2      31656             0
3      31657             0
4      31658             0
...      ...           ...
21097  52751             0
21098  52752             3
21099  52753             0
21100  52754             2
21101  52755             0

[21102 rows x 2 columns]

In [132]:
output.nunique()

ID              21102
MaterialType        3
dtype: int64

In [133]:
pd.unique(output['MaterialType'])

array([0, 3, 2])

In [134]:
output['MaterialType'].replace({0:'BOOK', 1:'SOUNDDISC', 2:'VIDEOCASS', 3:'VIDEODISC', 4:'SOUNDCASS',
       5:'MUSIC', 6:'MIXED', 7:'CR'}, inplace=True)
output


ID MaterialType
0      31654         BOOK
1      31655         BOOK
2      31656         BOOK
3      31657         BOOK
4      31658         BOOK
...      ...          ...
21097  52751         BOOK
21098  52752    VIDEODISC
21099  52753         BOOK
21100  52754    VIDEOCASS
21101  52755         BOOK

[21102 rows x 2 columns]

In [135]:
output.to_csv("sample_submission.csv", index=False)